apiVersion: v1
kind: Service
metadata:
    name: svc-client-np
    namespace: devops-test
spec:
    selector:
        app: cleint
    type: NodePort
    ports:
    - port: 3000
      targetPort: 3000
