apiVersion: v1
kind: Service
metadata:
    name: svc-client
    namespace: devops-test

spec:
    selector:
        app: client
    ports:
    - port: 3000
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
    name: svc-comments
    namespace: devops-test

spec:
    selector:
        app: comments
    ports:
    - port: 4001
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
    name: svc-moderation
    namespace: devops-test

spec:
    selector:
        app: moderation
    ports:
    - port: 4003
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
    name: svc-event-bus
    namespace: devops-test

spec:
    selector:
        app: event-bus
    ports:
    - port: 4005
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
    name: svc-posts
    namespace: devops-test

spec:
    selector:
        app: posts
    ports:
    - port: 4000
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
    name: svc-query
    namespace: devops-test

spec:
    selector:
        app: query
    ports:
    - port: 4002
      targetPort: 80
