- hosts: all
  become: yes

  tasks:
    - name: create the kube user account
      user: name=k8s-user append=yes state=present createhome=yes shell=/bin/bash

    - name: allow 'k8s-user' to use sudo without needing a password
      lineinfile:
        dest: /etc/sudoers
        line: 'kube ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: set up authorized keys for the kube user
      authorized_key: user=k8s-user key="{{item}}"
      with_file:
        - ~/.ssh/id_rsa.pub
